stages:
  - build
  - deploy

build_production:
  stage: build
  tags:
    - deploy
  only:
    - production
  image: lorisleiva/laravel-docker:latest
  before_script:
    - cp .env.prod.example .env
    - echo "RGAPI=${SECRET_API_KEY}" >> .env
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always


deploy_production:
  stage: deploy
  only:
    - production
  tags:
    - deploy
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f docker-compose.deploy.yml build
    - docker-compose -f docker-compose.deploy.yml down
    - docker-compose -f docker-compose.deploy.yml up -d --force-recreate
