stages:
    - build
    - test
    - deploy


composer:
  stage: build
  image: lorisleiva/laravel-docker:latest
  before_script:
    - cp .env.example .env
    - echo "RGAPI=${SECRET_API_KEY}" >> .env
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR12 --extensions=php app/Http/Controllers/ApiController.php

deploy:
  stage: deploy
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f docker-compose.deploy.yml build
    - docker-compose -f docker-compose.deploy.yml down
    - docker-compose -f docker-compose.deploy.yml up -d --force-recreate
