version: "3.8"

services:

  # API
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.8-alpine
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.chestgranted.middlewares=redirect-to-https"
      - "traefik.http.routers.chestgranted.rule=Host(`chestgranted.haakon.wtf`)"
      - "traefik.http.routers.chestgranted.entrypoints=web"
      - "traefik.http.routers.chestgranted-secure.rule=Host(`chestgranted.haakon.wtf`)"
      - "traefik.http.routers.chestgranted-secure.tls=true"
      - "traefik.http.routers.chestgranted-secure.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-proxy"
    networks:
      - bridge
      - traefik-proxy



networks:
  bridge:
    driver: bridge
  traefik-proxy:
    external: true
