version: "3.8"

services:

  # API
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bridge


networks:
  bridge:
    driver: bridge
