version: "3.8"

services:

  # API
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.4-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bridge



networks:
  bridge:
    driver: bridge
